### ISSUE TITLE
[NEW FEATURE] container name should be left-aligned

### ISSUE THREAD

**Issue by aljazerzen** [mrjackwills/oxker#39]
I'd wish container name would be left aligned in the "Containers" table.

![image](https://github.com/user-attachments/assets/c1bee268-a1c0-4056-b8f6-7e8e5ee3aa80)

This happens regularly when using docker compose.

**Comment by mrjackwills** [comment]
Thanks, I saw the PR, but I suspect that as is the tests will be failing.

I think that maybe the left align should/could be a command line argument, maybe `-l`, `--al`. Also, do you think that the header (in the screenshot above - `name` and `state`), should also be left aligned?

**Comment by aljazerzen** [comment]
From when I was working in UI for a corporate/industrial monitoring platform, the rule was that:
- all numberic fields are right-aligned, use the same unit and same number of decimal places. This makes them align with one another.
- all other fields are left-aligned because they often have similar prefixes.

I can add a command line argument, but I'm not sure there is a good case for text right alignment.

**Comment by mrjackwills** [comment]
Thank you, interesting rules.

As for left/right alignment, it was mainly because I, and I alone, thought it looked better right aligned. Still not 100% what the best thing for the headers are, especially as changing them from right to left aligned will mess up the white arrows used when sorting by each column - specially shifting the text, the arrows would need to become a suffix rather than the current prefix.

I'll have a play around with the PR, there is a new version to come out asap, with support for filtering containers & refactored tests, I am just waiting for Rust 1.80 to be released.
